import type { NextPage } from "next";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sagar Dev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Text fontSize="3xl" align="center">
          Sagar Dhandhalya
        </Text>
        <div style={{ width: "100vw", height: "100vh" }}>
          <Canvas>
            <OrbitControls />
            <ambientLight intensity={0.2} />
            <directionalLight color="red" position={[0, 0, 0]} />
            <mesh>
              <boxGeometry />
              <meshStandardMaterial />
            </mesh>
          </Canvas>
        </div>
      </div>
    </div>
  );
};

export default Home;
